<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2017-04-20
 * Time: 9:58
 */

namespace Colorcard\Controller;


use Common\Controller\AdminbaseController;

class AdminOfferController extends AdminbaseController
{
    protected $_model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Colorcard/Offer');
    }

    public function index(){
        if(IS_AJAX){
            $data['data'] = $this->_model->getRowsNoPaged();
            $data['status'] = 1;
            $this->ajaxReturn($data);
        }

        $tpls = D('Colorcard/Tpl')->getTplsNoPaged("isentity:1;");
        $this->assign('tpls', $tpls);
        $this->assign('qty_list', array(10,20,30,50,80,100));
        $this->display();
    }

    public function post(){
        if(IS_POST){
            $post = I('post.');
            if(!$post['tpl_id']){
                $this->error('请选择版式');
                return false;
            }
            $post['tpl_name'] = M('ColorcardTpl')->where("tpl_id=".$post['tpl_id'])->getField('tpl_name');
            $result = $this->_model->saveRow($post);
            if($result !== false){
                $this->success('已增加');
            }else{
                $this->error($this->_model->getError());
            }
        }
    }

}