<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-12-26
 * Time: 10:12
 */

namespace Colorcard\Controller;


use Common\Controller\AdminbaseController;

class AdminTplController extends AdminbaseController
{
    protected $_model;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Colorcard/Tpl');
    }

    function index(){
        $data = $this->_model->getTplsPaged();
        $this->assign('tpls', $data);
        $this->display();
    }

    function add(){
        $tplPageModel = M('ColorcardTplPage');
        $frcovers = $tplPageModel->field('pg_id,pg_name')->where(array('tpl_id'=>$id,'pg_type'=>4))->select();
        $bgcovers = $tplPageModel->field('pg_id,pg_name')->where(array('tpl_id'=>$id,'pg_type'=>5))->select();
        $this->assign('frcovers',$frcovers);
        $this->assign('bgcovers',$bgcovers);
        $this->display();
    }

    function add_post(){
        if(IS_POST){
            $post = I('post.');
            if($post['tpl_type']==2 && empty($post['show_type'])){
                $this->error("手机展示形式不能为空");
            }
            $post['tpl_css']=htmlspecialchars_decode($post['tpl_css']);
            $post['tpl_js']=htmlspecialchars_decode($post['tpl_js']);
            $result = $this->_model->addTpl($post);
            if($result !== false){
                $this->success('模板已添加',U('index'));
            }else{
                $this->error('保存失败！'.$this->_model->getError());
            }
        }
    }

    function edit($id){
        $tpl = $this->_model->getTpl($id);
        $tplPageModel = M('ColorcardTplPage');
        $frcovers = $tplPageModel->field('pg_id,pg_name')->where(array('tpl_id'=>$id,'pg_type'=>4))->select();
        $bgcovers = $tplPageModel->field('pg_id,pg_name')->where(array('tpl_id'=>$id,'pg_type'=>5))->select();
        $this->assign('frcovers',$frcovers);
        $this->assign('bgcovers',$bgcovers);
        $this->assign('data', $tpl);
        $this->display();
    }

    function edit_post(){
        if(IS_POST){
            $post = I('post.');
            $post['tpl_css']=htmlspecialchars_decode($post['tpl_css']);
            $post['tpl_js']=htmlspecialchars_decode($post['tpl_js']);
            $result = $this->_model->saveTpl($post);
            if($result !== false){
                $this->success('模板已更新！');
            }else{
                $this->error('保存失败！'.$this->_model->getError());
            }
        }
    }

}