<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-12-26
 * Time: 11:25
 */

namespace Colorcard\Controller;


use Common\Controller\AdminbaseController;

class AdminTplPageController extends AdminbaseController
{
    protected $_model;

    protected $tpl;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Colorcard/TplPage');
        $this->tpl = D('Colorcard/Tpl');
        $this->assign('pgTypes', $this->_model->types);
        
    }

    function index($id){
        $list = $this->_model->getPages($id,true);
        $this->assign('list', $list);
        $this->display();
    }

    function add($id){
        $tpl = $this->tpl->getTpl($id);
        $this->assign('tpl',$tpl);
        $this->display();
    }

    function add_post(){
        if(IS_POST){
            $post = I('post.');
            $post['pg_content']=htmlspecialchars_decode($post['pg_content']);
            $post['pg_css']=htmlspecialchars_decode($post['pg_css']);
            $post['pg_thumb'] = sp_asset_relative_url($post['pg_thumb']);
            $post['smeta'] = htmlspecialchars_decode($post['smeta']);
            $result = $this->_model->savePage($post);
            if($result !== false){
                $this->success('模板已添加',U('index',array('id'=>$post['tpl_id'])));
            }else{
                $this->error('保存失败！'.$this->_model->getError());
            }
        }
    }

    function edit($id){
        $data = $this->_model->find($id);
        $data['tpl']=$this->tpl = D('Colorcard/Tpl')->getTpl($data['tpl_id']);
        $this->assign('data',$data);
        $this->display();
    }

    function edit_post(){
        if(IS_POST){
            $post = I('post.');
            $post['pg_content']=htmlspecialchars_decode($post['pg_content']);
            $post['pg_css']=htmlspecialchars_decode($post['pg_css']);
            $post['pg_thumb'] = sp_asset_relative_url($post['pg_thumb']);
            $post['smeta'] = htmlspecialchars_decode($post['smeta']);
            $result = $this->_model->savePage($post);
            if($result !== false){
                $this->success('模板已更新！');
            }else{
                $this->error('保存失败！'.$this->_model->getError());
            }
        }
    }

}