<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-18
 * Time: 14:37
 */

namespace Admin\Controller;


use Common\Controller\AdminbaseController;

class ShippingController extends AdminbaseController
{
    protected $_model;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Shipping');
    }

    function index(){
        $list = $this->_model->getShippingPaged();
        $this->assign('list',$list);
        $this->display();
    }

    function add(){
        $this->display();
    }

    function add_post(){
        if(IS_POST){
            $post = I('post.');
            $result = $this->_model->addShipping($post);
            if($result > 0){
                $this->success('添加成功！',U('index'));
            }else{
                $this->mGetErrorByCode($result);
            }
        }
    }

    function edit($id){
        $Shipping = $this->_model->getShipping($id);
        $this->assign($Shipping);
        $this->display();
    }

    function edit_post(){
        if(IS_POST){
            $post = I('post.');
            $result = $this->_model->updateShipping($post);
            if($result > 0){
                $this->success('保存成功！');
            }else{
                $this->mGetErrorByCode($result);
            }
        }
    }

}