CREATE TABLE `mlg_order_action` (
  `action_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '流水号',
  `order_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '被操作的交易号',
  `action_user` varchar(30) NOT NULL COMMENT '操作该次的人员',
  `order_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '作何操作.0，未确认；1，已确认；2，已取消；3，无效；4，退货；',
  `shipping_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '发货状态。0，未发货；1，已发货；2，已收货；3，备货中',
  `pay_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '支付状态.0,未付款;1,付款中;2,已付款;',
  `action_place` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '操作位置：0订单，1发货单，2退货单',
  `action_note` varchar(255) NOT NULL COMMENT '操作备注',
  `log_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '操作时间',
  PRIMARY KEY (`action_id`),
  KEY `order_id` (`order_id`)
) ENGINE=MyISAM AUTO_INCREMENT=74 DEFAULT CHARSET=utf8 COMMENT='对订单操作日志表';

CREATE TABLE `mlg_order_goods` (
  `rec_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '订单商品信息自增id',
  `order_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '订单商品信息对应的详细信息id，取值order_info的order_id',
  `goods_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商品的的id',
  `goods_name` varchar(120) NOT NULL COMMENT '商品的名称',
  `goods_sn` varchar(60) NOT NULL COMMENT '商品的唯一货号',
  `goods_number` smallint(5) unsigned NOT NULL DEFAULT '1' COMMENT '商品的购买数量',
  `goods_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品的售价',
  `goods_sku` text COMMENT '购买该商品时所选择的sku；',
  `parent_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '父商品id，取值于mlg_cart的parent_id；如果有该值则是值多代表的物品的配件',
  `goods_sku_id` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`rec_id`),
  KEY `order_id` (`order_id`),
  KEY `goods_id` (`goods_id`)
) ENGINE=MyISAM AUTO_INCREMENT=75 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='订单的商品信息，注：订单的商品信息基本都是从购物车所对应的表中取来的。';

CREATE TABLE `mlg_order_info` (
  `order_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '订单详细信息自增id',
  `order_sn` varchar(20) NOT NULL COMMENT '订单号，唯一',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户id，同mlg_users的id',
  `supplier_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '供应商id',
  `order_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '订单状态。0，未确认；1，已确认；2，已取消；3，无效；4，退货；',
  `shipping_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '商品配送情况，0，未发货；1，已发货；2，已收货；3，备货中',
  `pay_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '支付状态；0，未付款；1，付款中；2，已付款',
  `consignee` varchar(60) NOT NULL COMMENT '收货人的姓名，用户页面填写，默认取值于表user_address',
  `country` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '收货人的国家，用户页面填写，默认取值于表user_address，其id对应的值在mlg_areas',
  `province` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '收货人的省份，用户页面填写，默认取值于表user_address，其id对应的值在mlg_areas',
  `city` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '收货人的城市，用户页面填写，默认取值于表user_address，其id对应的值在mlg_areas',
  `district` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '收货人的地区，用户页面填写，默认取值于表user_address，其id对应的值在mlg_areas',
  `address` varchar(255) NOT NULL COMMENT '收货人的详细地址，用户页面填写，默认取值于表user_address',
  `zipcode` varchar(60) NOT NULL COMMENT '收货人的邮编，用户页面填写，默认取值于表user_address',
  `tel` varchar(60) NOT NULL COMMENT '收货人的电话，用户页面填写，默认取值于表user_address',
  `mobile` varchar(60) NOT NULL COMMENT '收货人的手机，用户页面填写，默认取值于表user_address',
  `email` varchar(60) NOT NULL COMMENT '收货人的邮箱，用户页面填写，默认取值于表user_address',
  `best_time` varchar(120) NOT NULL COMMENT '收货人的最佳送货时间，用户页面填写，默认取值于表user_address',
  `sign_building` varchar(120) NOT NULL COMMENT '收货人的地址的标志性建筑，用户页面填写，默认取值于表user_address',
  `postscript` varchar(255) NOT NULL COMMENT '订单附言，由用户提交订单前填写',
  `shipping_id` tinyint(3) NOT NULL DEFAULT '0' COMMENT '用户选择的配送方式id，取值表mlg_shipping',
  `shipping_name` varchar(120) NOT NULL COMMENT '用户选择的配送方式的名称，取值表mlg_shipping',
  `pay_id` tinyint(3) NOT NULL DEFAULT '0' COMMENT '用户选择的支付方式的id，取值表mlg_payment',
  `pay_name` varchar(120) NOT NULL COMMENT '用户选择的支付方式的名称，取值表mlg_payment',
  `goods_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品总金额',
  `shipping_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '配送费用',
  `insure_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '保价费用',
  `pay_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '支付费用,跟支付方式的配置相关，取值表mlg_payment',
  `order_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '应付款金额',
  `add_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '订单生成时间',
  `confirm_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '订单确认时间',
  `pay_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '订单支付时间',
  `shipping_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '订单配送时间',
  `invoice_no` varchar(50) NOT NULL COMMENT '发货单号，发货时填写，可在订单查询查看',
  `to_buyer` varchar(255) NOT NULL COMMENT '商家给客户的留言,当该字段有值时可以在订单查询看到',
  `pay_note` varchar(255) NOT NULL COMMENT '付款备注，在订单管理里编辑修改',
  `inv_type` varchar(60) NOT NULL COMMENT '发票类型，用户页面选择',
  `inv_payee` varchar(120) NOT NULL COMMENT '发票抬头，用户页面填写',
  `inv_content` varchar(120) NOT NULL COMMENT '发票内容，用户页面选择，取值mlg_shop_config的code字段的值为invoice_content的value',
  `tax` decimal(10,2) NOT NULL COMMENT '发票税额',
  `discount` decimal(10,2) NOT NULL COMMENT '折扣金额',
  `is_colorcard` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否色卡订单 0否1是',
  `order_trash` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `order_sn` (`order_sn`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=69 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='订单的详细信息';

CREATE TABLE `mlg_user_address` (
  `address_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `address_name` varchar(50) NOT NULL DEFAULT '',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户表中的流水号',
  `consignee` varchar(60) NOT NULL DEFAULT '' COMMENT '收货人的名字',
  `email` varchar(60) NOT NULL DEFAULT '' COMMENT '收货人的email',
  `country` int(11) NOT NULL DEFAULT '0' COMMENT '收货人的国家',
  `province` int(11) NOT NULL DEFAULT '0' COMMENT '收货人的省份',
  `city` int(11) NOT NULL DEFAULT '0' COMMENT '收货人的城市',
  `district` int(11) NOT NULL DEFAULT '0' COMMENT '收货人的地区',
  `address` varchar(120) NOT NULL DEFAULT '' COMMENT '收货人的详细地址',
  `zipcode` varchar(60) NOT NULL DEFAULT '' COMMENT '收货人的邮编',
  `tel` varchar(60) NOT NULL DEFAULT '' COMMENT '收货人的电话',
  `mobile` varchar(60) NOT NULL DEFAULT '' COMMENT '收货人的手机',
  `sign_building` varchar(120) NOT NULL DEFAULT '' COMMENT '收货地址的标志性建筑名',
  `best_time` varchar(120) NOT NULL DEFAULT '' COMMENT '收货人的最佳收货时间',
  `created_time` int(11) unsigned NOT NULL,
  `modified_time` int(11) unsigned NOT NULL,
  PRIMARY KEY (`address_id`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=27 DEFAULT CHARSET=utf8;

CREATE TABLE `mlg_cart` (
  `rec_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID号',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户登录id，取自session，',
  `session_id` char(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '登录的sessionid，如果该用户退出，该sessionid对应的购物车中的所有记录都将被删除',
  `goods_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商品的id，取自表textile_fabric的tf_id或colorcard的card_id',
  `goods_sn` varchar(60) NOT NULL COMMENT '商品的货号，取自表textile_fabric的code或colorcard的card_no',
  `goods_name` varchar(120) NOT NULL COMMENT '商品的名称，取自表textile_fabric的name或colorcard的card_name',
  `goods_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品的本店价，取自表textile_fabric的price',
  `goods_number` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '商品的购买数量，在购物车时，实际库存不减少',
  `goods_sku` varchar(3000) NOT NULL COMMENT '商品的sku',
  `is_colorcard` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否色卡，0，否；1，是',
  `parent_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '该商品的父商品id，没有该值为0，有的话那该商品就是该id的配件',
  `can_handsel` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '能否处理，0，否；1，是',
  `goods_sku_id` int(10) unsigned NOT NULL DEFAULT '0',
  `supplier_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '供应商id',
  `is_checked` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否选中',
  PRIMARY KEY (`rec_id`),
  KEY `session_id` (`session_id`)
) ENGINE=MyISAM AUTO_INCREMENT=111 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='购物车购物信息记录表';

CREATE TABLE `mlg_delivery_order` (
  `delivery_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `delivery_sn` varchar(20) NOT NULL COMMENT '发货单号',
  `order_sn` varchar(20) NOT NULL COMMENT '订单号',
  `order_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '订单id',
  `invoice_no` varchar(50) DEFAULT NULL COMMENT '快递单号',
  `add_time` int(10) unsigned DEFAULT '0' COMMENT '添加时间',
  `shipping_id` tinyint(3) unsigned DEFAULT '0' COMMENT '配送方式id',
  `shipping_name` varchar(120) DEFAULT NULL COMMENT '配送方式',
  `user_id` int(11) unsigned DEFAULT '0' COMMENT '用户id',
  `supplier_id` int(10) unsigned NOT NULL DEFAULT '0',
  `action_user` varchar(30) DEFAULT NULL COMMENT '操作管理员id',
  `consignee` varchar(60) DEFAULT NULL,
  `address` varchar(250) DEFAULT NULL,
  `country` int(10) unsigned DEFAULT '0',
  `province` int(10) unsigned DEFAULT '0',
  `city` int(10) unsigned DEFAULT '0',
  `district` int(10) unsigned DEFAULT '0',
  `sign_building` varchar(120) DEFAULT NULL,
  `email` varchar(60) DEFAULT NULL,
  `zipcode` varchar(60) DEFAULT NULL,
  `tel` varchar(60) DEFAULT NULL,
  `mobile` varchar(60) DEFAULT NULL,
  `best_time` varchar(120) DEFAULT NULL,
  `postscript` varchar(255) DEFAULT NULL COMMENT '附言',
  `insure_fee` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '保价费用',
  `shipping_fee` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '运费',
  `update_time` int(10) unsigned DEFAULT '0' COMMENT '更新时间',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`delivery_id`),
  KEY `user_id` (`user_id`),
  KEY `order_id` (`order_id`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

CREATE TABLE `mlg_delivery_goods` (
  `rec_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `delivery_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '发货单id',
  `goods_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商品id',
  `goods_name` varchar(120) DEFAULT NULL COMMENT '商品名称',
  `goods_sn` varchar(60) DEFAULT NULL COMMENT '商品编号',
  `parent_id` int(11) unsigned DEFAULT '0',
  `send_number` smallint(5) unsigned DEFAULT '0' COMMENT '发货数量',
  `goods_sku` text COMMENT 'sku信息',
  PRIMARY KEY (`rec_id`),
  KEY `delivery_id` (`delivery_id`,`goods_id`),
  KEY `goods_id` (`goods_id`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;

CREATE TABLE `mlg_payment` (
  `pay_id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT COMMENT '已安装的支付方式自增id',
  `pay_code` varchar(20) NOT NULL COMMENT '支付方式的英文缩写，其实就是该支付方式处理插件的不带后缀的文件名部分',
  `pay_name` varchar(120) NOT NULL COMMENT '支付方式名称',
  `pay_fee` varchar(10) NOT NULL DEFAULT '0' COMMENT '支付费用',
  `pay_desc` text NOT NULL COMMENT '支付方式描述',
  `pay_order` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '支付方式在页面的显示顺序',
  `pay_config` text NOT NULL COMMENT '支付方式的配置信息，包括商户号和密钥什么的',
  `enabled` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否可用，0，否；1，是',
  PRIMARY KEY (`pay_id`),
  UNIQUE KEY `pay_code` (`pay_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='安装的支付方式配置信息';
