<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-18
 * Time: 14:37
 */

namespace Address\Controller;


use Common\Controller\AdminbaseController;

class AdminController extends AdminbaseController
{
    protected $_model;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Address/Address');
    }

    function index(){
        $list = $this->_model->getAddressPaged();
        $this->assign('list',$list);
        $this->display();
    }

    function add($id){
        $user = D('Users')->getUser($id);
        $this->assign('user',$user);
        $this->display();
    }

    function add_post(){
        if(IS_POST){
            $post = I('post.');
            $result = $this->_model->addAddress($post);
            if($result > 0){
                $this->success('添加成功！',U('index'));
            }else{
                $this->mGetErrorByCode($result);
            }
        }
    }

    function edit($id){
        $address = $this->_model->getAddress($id);
        $this->assign($address);
        $this->assign('areas',D('Areas')->getAreasByDistrict($address['district']));
        $this->display();
    }

    function edit_post(){
        if(IS_POST){
            $post = I('post.');
            $result = $this->_model->updateAddress($post);
            if($result > 0){
                $this->success('保存成功！');
            }else{
                $this->mGetErrorByCode($result);
            }
        }
    }

    function search(){
        $where['user_status'] = 1;
        $where['user_type'] = 20;

        if(isset($_GET['term'])){
            if($_GET['method'] == 'eq'){
                $where['nickname'] = $_GET['term'];
            }else{
                $where['nickname'] = array('LIKE','%'.$_GET['term'].'%');
            }
        }

        //$data['query'] = $_GET['query'];
        $data = D("Users")
        ->field('id,nickname,user_login')
            ->where($where)
            ->select();
        foreach($data as $key =>$value){
            if(empty($data[$key]['nickname'])){
                $data[$key]['uname'] = $data[$key]['user_login'];
            }else{
                $data[$key]['uname'] = $data[$key]['nickname'];
            }    
        }
        header('Content-Type:application/json; charset=utf-8');
        exit(json_encode($data));
    }

}