<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-19
 * Time: 11:39
 */

namespace Notify\Controller;


use Common\Controller\AdminbaseController;

class AdminController extends AdminbaseController
{
    protected $_model;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Notify/Msg');
    }

    function index(){
        $sender_type = I('request.stype/d', 0);
        $msgs = $this->_model->getMsgsPaged("sender_type:$sender_type;");
        $this->assign('msgs', $msgs);
        $this->display();
    }

    public function send($id, $type = 1)
    {
        $this->assign('receiver_id', $id);
        $this->assign('receiver_type', $type);
        $receiver_name = $this->_model->get_name($id, $type);
        $this->assign('receiver_name', $receiver_name);
        $this->display();
    }

    public function send_post()
    {
        if (IS_POST) {
            $post = I('post.');
            $receiver_id = $post['receiver_id'];
            $receiver_type = $post['receiver_type'];
            $title = $post['title'];
            $content = I('post.content');
            $result = $this->_model->sendMsg($receiver_id, $title, $content, session('ADMIN_ID'), 3, $receiver_type);
            if ($result !== false) {
                $msg = $this->_model->getMsg($result);
                $this->assign($msg);
                $html = $this->fetch('tpl_msg');
                $this->ajaxReturn(array(
                    'status'=> 1,
                    'info'  => '消息已发送！',
                    'html'  => $html,
                ));
            } else {
                $this->error($this->_model->getError());
            }
        }
    }

    function action_log($id){
        $logs = D('Log')->getLogsNoPaged("message_id:$id");
        $this->ajaxReturn($logs);
    }
}