<?php
namespace Notify\Controller;
use Common\Controller\MemberbaseController;

class BmController extends MemberbaseController {

    protected $_model;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Notify/Msg');
    }

    function index(){
        $uid = $this->userid;
        $readed = isset($_GET['read']) ? "readed:".I('get.read').";":'';
	    $msgs = $this->_model->getMsgsPaged("receiver_id:$uid;receiver_type:1;$readed");
        $this->assign('msgs',$msgs);
	    $this->display();
	}

	function read(){
	    if(IS_POST){
	        $where['message_id'] = I('post.id');
            $where['receiver_id'] = $this->userid;
            $result = $this->_model->setRead($where);
            if($result){
                $this->success('操作成功！');
            }else{
                $this->error('操作失败！'.$this->_model->getError());
            }
        }
    }

    function delete(){
        if(IS_POST){
            $where['message_id'] = I('post.id');
            $where['receiver_id'] = $this->userid;
            $result = $this->_model->setDeleted($where);
            if($result){
                $this->success('操作成功！');
            }else{
                $this->error('操作失败！'.$this->_model->getError());
            }
        }
    }
}