<?php
namespace Notify\Controller;

use Common\Controller\SupplierbaseController;

class SupplierController extends SupplierbaseController
{

    protected $_model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Notify/Msg');
    }

    public function index()
    {
        $member_id = $this->memberid;
        $readed = isset($_GET['read']) ? "readed:".I('get.read').";":'';
        $msgs = $this->_model->getMsgsPaged("receiver_id:$member_id;receiver_type:2;$readed");
        $this->assign('msgs', $msgs);
        $this->display();
    }

    public function read(){
        if(IS_POST){
            $where['message_id'] = I('post.id');
            $where['receiver_id'] = $this->memberid;
            $result = $this->_model->setRead($where);
            if($result){
                $this->success('操作成功！');
            }else{
                $this->error('操作失败！'.$this->_model->getError());
            }
        }
    }

    public function delete(){
        if(IS_POST){
            $where['message_id'] = I('post.id');
            $where['receiver_id'] = $this->memberid;
            $result = $this->_model->setDeleted($where);
            if($result){
                $this->success('操作成功！');
            }else{
                $this->error('操作失败！'.$this->_model->getError());
            }
        }
    }
}
