<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-28
 * Time: 9:21
 */

namespace Common\Controller;


class SupplierbaseController extends MemberbaseController
{
    protected $bm_model;
    protected $member;
    protected $memberid;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->bm_model = D('BizMember');

        $this->check_auth();

        $this->member = $this->user['member'];
        $this->memberid = $this->member['id'];
        $this->operatorid = $this->user['operator']['id'];
        $this->assign('member', $this->member);

        if ($this->user['operator']['is_expired'] == 1) {
            $this->error('您的运营人员权限已经过期了，请通知面料商运营管理人员更新您的有效期限！');
        }

        if (!$this->check_access($this->user['operator']['id'])) {
            $this->error("您没有访问权限！");
        }

        $supplierNotifyNum = M('SupplierNotifyNum')->where("supplier_id='{$this->memberid}'")->find();
        $this->assign('notify_num', $supplierNotifyNum);
    }

    function check_auth(){
        if(empty($this->user['member'])){
            $this->error('您不是供应商！',leuu("Bizauth/Index/index"));
        }

        if($this->user['member']['authenticated'] == 0){
            $this->error('您的账号还没有通过认证！',leuu("Bizauth/Index/index"));
        }
    }

    private function check_access($opid)
    {
        //如果用户角色是1，则无需判断
        /*if($opid == 1){
            return true;
        }*/

        $rule=MODULE_NAME.CONTROLLER_NAME.ACTION_NAME;
        $no_need_check_rules = array("SupplierCenterIndex",);

        if (!in_array($rule, $no_need_check_rules)) {
            return opauth_check($opid);
        } else {
            return true;
        }
    }
}
