<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2017-04-14
 * Time: 10:11
 */

namespace Account\Controller;


use Common\Controller\SupplierbaseController;
use Wx\Common\Wechat;

class RechargeController extends SupplierbaseController
{
    protected $_model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Account/Recharge');
    }

    public function index()
    {
        $this->display();
    }

    public function logs()
    {
        if (IS_AJAX) {
            $member_id = $this->memberid;
            $data['data'] = $this->_model->getRowsNoPaged("member_id:$member_id;trash:0;");
            $data['status'] = 1;
            $this->ajaxReturn($data);
        }
        $this->display();
    }

    public function create_post()
    {
        if (IS_POST) {
            $post = I('post.');
            $result = $this->_model->recharge($this->memberid, $post['recharge_money'], $this->userid, $post['remark']);
            if ($result !== false) {
                $this->ajaxReturn(array(
                    'status' => 1,
                    'url' => leuu('Wx/Pay/recharge', array('id' => $result)),
                ));
            } else {
                $this->error($this->_model->getError());
            }
        }
    }

    function cancel($id)
    {
        if (IS_POST) {
            $where['id'] = $id;
            $where['member_id'] = $this->memberid;
            $result = $this->_model->cancel($where);
            if ($result !== false) {
                $this->success('操作成功！');
            } else {
                $this->error($this->_model->getError());
            }

        }
    }


    public function pay_success($id)
    {
        $this->display();
    }

}