<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-04
 * Time: 10:32
 */

namespace Demand\Controller;


use Common\Controller\AdminbaseController;

class AdminQuoteController extends AdminbaseController
{
    protected $quote_model;
    protected $quote_trash = 0;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->quote_model = D('Quote');
    }

    function index(){
        $where = array();
        $where['quote_trash'] = $this->quote_trash;
        $quotes = $this->quote_model->getQuotesPaged($where);

        $this->assign('quotes', $quotes);
        $this->display();
    }

    /**
     *  删除
     */
    public function delete() {
        if(IS_POST){
            $result = $this->quote_model->where(array('quote_id'=>I('post.id')))->save(array('quote_trash'=>1));
            if($result !== false){
                $this->success('删除成功！',U('index'));
            }else{
                $this->error('删除失败！'.$this->quote_model->getError());
            }
        }
    }

    /**
     *  审核
     */
    function check(){

        if(IS_POST){
            if($_GET["pass"]){
                $result = $this->quote_model->where(array('quote_id'=>I('post.id')))->save(array('quote_status'=>1));
                if ( $result!==false) {
                    $this->success("审核成功！",U('index'));
                } else {
                    $this->error("审核失败！".$this->quote_model->getError());
                }
            }
            if($_GET["nopass"]){
                $result = $this->quote_model->where(array('quote_id'=>I('post.id')))->save(array('quote_status'=>0));
                if ( $result!==false) {
                    $this->success("取消审核成功！",U('index'));
                } else {
                    $this->error("取消审核失败！".$this->quote_model->getError());
                }
            }
        }
        
    }
        
}