<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-15
 * Time: 11:30
 */

namespace Cart\Controller;


use Common\Controller\MemberbaseController;

class IndexController extends MemberbaseController
{
    protected $_model;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Cart/Cart');
    }

    function index(){
        $user_id = sp_is_user_login() ? sp_get_current_userid():session_id();
        $cart = $this->_model->getCart($user_id,null,true);
        $this->assign('cart', $cart);

//        var_dump($cart);

        if(sp_is_user_login()){
            $address = D('Address/Address')->getAddressPaged('',array('user_id'=>$user_id));
            $address['default'] = $this->user['address_id'];
            $this->assign('address',$address);
        }
        $shipping = D('Shipping')->getShippingPaged();
        $this->assign('shipping',$shipping);

        $this->display();
    }

    function add_item(){
        $user_id = sp_is_user_login() ? sp_get_current_userid():session_id();
        $post = I('post.');
        $sku_id = $post['sku_id'];
        $number = $post['number'];
        $result = $this->_model->addColorboardItem($user_id,$sku_id,$number);
        $allNum = $this->_model->getAllItemsCount($user_id);
        if($result){
            $this->success('已添加到购物车！','',false,$allNum);
        }else{
            $this->error('操作失败！'.$this->_model->getError());
        }
    }

    function remove_item(){
        if(sp_is_user_login()){
            $where['user_id'] = sp_get_current_userid();
        }else{
            $where['session_id'] = session_id();
        }
        $where['rec_id'] = I('post.id');
        $result = $this->_model->removeItem($where);
        if($result !== false){
            $total = $this->_model->getTotal($this->userid);
            $this->success($total);
        }else{
            $this->error($this->_model->getError());
        }
    }

    function clean(){
        $user_id = sp_is_user_login() ? sp_get_current_userid():session_id();
        $result = $this->_model->cleanAllItems($user_id);
        $this->ajaxReturn($result);
    }

    function change_num(){
        $post = I('post.');
        $where['rec_id'] = $post['id'];
        if(sp_is_user_login()){
            $where['user_id'] = sp_get_current_userid();
        }else{
            $where['session_id'] = session_id();
        }
        $result = $this->_model->changeNum($where, $post['number']);
        if($result !== false){
            $total = $this->_model->getTotal($this->userid);
            $this->success($total);
        }else{
            $this->error('操作失败！');
        }
    }

    function check_goods(){
        if(IS_POST){
            $post = I('post.');
            if(sp_is_user_login()){
                $where['user_id'] = sp_get_current_userid();
            }else{
                $where['session_id'] = session_id();
            }
            if(isset($post['id'])){
                $where['rec_id'] = $post['id'];
            }
            if(isset($post['supplier_id'])){
                $where['supplier_id'] = $post['supplier_id'];
            }
            $is_checked = $post['is_checked'];
            $result = $this->_model->check($where,$is_checked);
            if($result){
                $total = $this->_model->getTotal($this->userid);
                $this->success($total);
            }else{
                $this->error('操作失败！'.$this->_model->getError());
            }
        }
    }

    function checkout(){
        $cart = $this->_model->getCart($this->userid,null,true);
        $this->assign('cart', $cart);

        $addresses = D('Address/Address')->getAddressNoPaged(array('user_id'=>$this->userid));
        $this->assign('addresses',$addresses);

        if(array_key_exists($this->user['address_id'], $addresses)){
            $default_address = $addresses[$this->user['address_id']];
        }else{
            $default_address = reset($addresses);
        }
        $this->assign('address', $default_address);

        $shippings = D('Shipping')->getShippingNoPaged();
        $this->assign('shippings',$shippings);
        $this->assign('shipping',reset($shippings));
        $this->display();
    }

}