<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-19
 * Time: 10:00
 */

namespace Order\Controller;


use Common\Controller\SupplierbaseController;

class CardController extends SupplierbaseController
{
    protected $_model;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Order', 'Logic');
        $this->assign('order_statuses', $this->_model->orderStatuses);
        $this->assign('pay_statuses', $this->_model->payStatuses);
        $this->assign('shipping_statuses', $this->_model->shippingStatuses);
    }

    function index(){
        if(sp_is_mobile() && !IS_AJAX){
            $this->display();
            exit();
        }

        if(isset($_REQUEST['status'])){
            $_REQUEST['filter']['status'] = $_REQUEST['status'];
        }

        if(isset($_REQUEST['filter'])){
            $filter = I('request.filter');
            if(isset($filter['status'])){
                $where['order_status'] = array('IN','0,1');
                switch($filter['status']){
                    case 'unpaid':
                        $where['pay_status'] = array('IN','0,1');
                        $where['shipping_status'] = 0;
                        if(isset($_REQUEST['status'])) $this->assign('unpaid_active', 'active');
                        break;
                    case 'unshipped':
                        $where['pay_status'] = 2;
                        $where['shipping_status'] = array('IN', '0,3,4');
                        if(isset($_REQUEST['status'])) $this->assign('unshipped_active', 'active');
                        break;
                    case 'unreceived':
                        $where['pay_status'] = 2;
                        $where['shipping_status'] = 1;
                        if(isset($_REQUEST['status'])) $this->assign('unreceived_active', 'active');
                        break;
                    case 'received':
                        $where['pay_status'] = 2;
                        $where['shipping_status'] = 2;
                        if(isset($_REQUEST['status'])) $this->assign('received_active', 'active');
                        break;
                    case 'closed':
                        $where['order_status'] = array('IN','2,3');
                        $where['pay_status'] = 0;
                        $where['shipping_status'] = 0;
                        if(isset($_REQUEST['status'])) $this->assign('received_active', 'active');
                        break;
                    case 'refunded':
                        $where['order_status'] = 4;
                        $where['pay_status'] = 0;
                        $where['shipping_status'] = 0;
                        if(isset($_REQUEST['status'])) $this->assign('received_active', 'active');
                        break;
                    default:
                        unset($where['order_status']);
                        if(isset($_REQUEST['status'])) $this->assign('default_active', 'active');

                }
            }
            if(!empty($filter['keywords'])){
                $where['order_sn'] = array('LIKE','%'.$filter['keywords'].'%');
            }
            if(!empty($filter['datestart']) && !empty($filter['datestart'])){
                $where['add_time'] = array('between', strtotime($filter['datestart']) . ',' . strtotime($filter['datefinish']));
            }elseif(!empty($filter['datestart']) && empty($filter['datestart'])){
                $where['add_time'] = array('egt', strtotime($filter['datestart']));
            }elseif(empty($filter['datestart']) && !empty($filter['datestart'])){
                $where['add_time'] = array('elt', strtotime($filter['datefinish']));
            }
            $this->assign('filter',$filter);
        }

        $where['is_colorcard'] = 1;
        $where['user_id'] = $this->memberid;
        $this->assign('is_colorcard',1);
        $orders = $this->_model->getOrdersPaged($where);
        $this->assign('orders', $orders);
        if(IS_AJAX){
            $html = $this->fetch('more');
            $data['html'] = $html;
            $data['totalPages'] = $orders['totalPages'];
            $this->ajaxReturn($data);
        }else{
            $this->display();
        }
    }

    function view(){
        $where['order_id'] = I('get.id');
        $where['user_id'] = $this->memberid;
        $order = $this->_model->getOrder($where);
        $this->assign($order);
        $this->display();
    }

    public function easy_order(){
        $card_id = I('get.id/d', 0);
        $card = D('Colorcard/Colorcard')->find($card_id);

        if (empty($card)) {
            $this->error('传入数据错误！');
        }

        $this->assign('card', $card);

        $addresses = D('Address/Address')->getAddressNoPaged(array('user_id'=>$this->userid));
        $this->assign('addresses',$addresses);

        $shippings = D('Shipping')->getShippingNoPaged();
        $this->assign('shippings',$shippings);

        $this->display();
    }

    function easy_order_post(){
        if(IS_POST){
            $post = I('post.');
            $aid = $post['address_id'];
            $sid = $post['shipping_id'];
            $card_id = $post['card_id'];
            $number = $post['goods_number'];
            $ps = $post['postscript'];

            if(empty($number) || !is_numeric($number)){
                $this->error('请选择购买的数量！');
            }
            if(empty($aid) || !is_numeric($aid)){
                $this->error('请选择收货地址！');
            }
            if(empty($sid) || !is_numeric($sid)){
                $this->error('请选择配送方式！');
            }

            $address = D('Address/Address')->find($aid);
            if (empty($address)) {
                $this->error('传入数据错误！');
            }
            unset($address['user_id']);

            $shipping = D('Shipping')->find($sid);
            if (empty($shipping)) {
                $this->error('传入数据错误！');
            }
            unset($shipping['user_id']);

            $result = $this->_model->buildCardEasyOrder($card_id, $number, $this->memberid, $address, $shipping, $ps,false);
            if($result){
                /*$this->ajaxReturn(array(
                    'data'  => $result,
                    'sid'   => $this->memberid,
                    'status'=> 0,
                    'info'  => 'debug',
                ));*/
                $this->success('已下单！',leuu('view',array('id'=>$result)));
            }else{
                $this->error('操作失败！'.$this->_model->getError());
            }
        }
    }

    function receive(){
        if(IS_POST){
            $id = I('post.id');
            $where['order_id'] = $id;
            $where['user_id'] = $this->memberid;
            $where['shipping_status'] = 1;
            $order = $this->_model->getOrder($where);
            if($order){
                $result = $this->_model->setReceived($id);
                if($result !== false){
                    $this->success('操作成功！',leuu('view',array('id'=>$id)));
                }else{
                    $this->error($this->_model->getError());
                }
            }else{
                $this->error('错误的操作！');
            }
        }
    }

    function cancel(){
        if(IS_POST){
            $id = I('post.id');
            $where['order_id'] = $id;
            $where['user_id'] = $this->memberid;
            $where['shipping_status'] = 1;
            $order = $this->_model->getOrder($where);
            if($order){
                $result = $this->_model->cancel($id);
                if($result !== false){
                    $this->success('操作成功！',leuu('view',array('id'=>$id)));
                }else{
                    $this->error($this->_model->getError());
                }
            }else{
                $this->error('错误的操作！');
            }
        }
    }

    function delete(){
        if(IS_POST){
            $id = I('post.id');
            $where['user_id'] = $this->memberid;
            $where['order_status'] = array('IN','2,3');
            $order = $this->_model->getOrder($where);
            if($order){
                $result = $this->_model->trash($id);
                if($result !== false){
                    $this->success('操作成功！',leuu('index'));
                }else{
                    $this->error($this->_model->getError());
                }
            }else{
                $this->error('错误的操作！');
            }
        }
    }
}