<?php
namespace Collect\Controller;
use Common\Controller\MemberbaseController;

class IndexController extends MemberbaseController
{

    protected $_model;
    protected $_colorboard;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Collect');
        $this->_colorboard = D("CollectColorboard");
    }

    function index(){

        $type = I('get.type/d',1);
        $this->assign('type',$type);
        
        // if(sp_is_mobile() && !IS_AJAX){
        //     $this->display();
        //     exit();
        // }
        

        $uid = $this->userid;
        $data = $this->_model->getCollPaged("user_id:$uid;type:$type;",10);

        $data['type'] = $type;
        $this->assign('data', $data);
        if(IS_AJAX){
            $html = $this->fetch('more');
            $data['html'] = $html;
            $this->ajaxReturn($data);
        }else{
            $this->display();
        }
	}

    function colorboard(){
        if(sp_is_mobile() && !IS_AJAX){
            $this->display();
            exit();
        }
        $type = I('get.type/d',1);
        $this->assign('type',$type);
        $uid = $this->userid;
        $data = $this->_colorboard->getCollPaged("user_id:$uid;type:$type;",10);
        $data['type'] = $type;
        $tmp = array();

        foreach ($data['data'] as $key => $value) {
            $createDate = mb_substr($value['create_date'], 0, 10);
            $tmp[$createDate][] = $value;
        }

        $data['data'] = $tmp;

        $this->assign('data', $data);

        if(IS_AJAX){
            $html = $this->fetch('more_colorboard');
            $data['html'] = $html;
            $this->ajaxReturn($data);
        }else{
            $this->display();
        }
    }

	function toggle(){
        $goods_id = I('request.id');
        $type = I('request.type');

        if ($type == 3) {
            $Wx = new \Wx\Common\Wechat();
            list($err, $user_info) = $Wx->api->get_user_info($_SESSION['user']['openid']);

            if (!$user_info->subscribe) {
                $data = array(
                    'info'  => '请先关注面料馆公众号',
                    'status'=> 0,
                    'url'   => '',
                    'data'  => ''
                );
            }

        }

        $uid = $this->userid;
        $result = $this->_model->toggle($goods_id, $uid, $type);
        $collect = $this->_model
            ->where(array('goods_id'=>$goods_id,'user_id'=>$uid,'type'=>$type))
            ->find();
        if(empty($collect)){
            $collect = array('goods_id'=>$goods_id);
        }
        if($result > 0){
            $data = array(
                'info'  => '操作成功',
                'status'=> 1,
                'url'   => '',
                'data'  => $collect
            );
        }else{
            $data = array(
                'info'  => '操作失败！'.$this->_model->getError(),
                'status'=> 0,
                'url'   => '',
                'data'  => $collect
            );
        }
        $this->ajaxReturn($data);
    }

    function toggleColorboard(){
        $goods_id = I('request.id');
        $type = I('request.type');
        $uid = $this->userid;
        $result = $this->_colorboard->toggle($goods_id, $uid, $type);
        $collect = $this->_colorboard
            ->where(array('goods_id'=>$goods_id,'user_id'=>$uid,'type'=>$type))
            ->find();
        if(empty($collect)){
            $collect = array('goods_id'=>$goods_id);
        }
        if($result > 0){
            $data = array(
                'info'  => '操作成功',
                'status'=> 1,
                'url'   => '',
                'data'  => $collect
            );
        }else{
            $data = array(
                'info'  => '操作失败！'.$this->_colorboard->getError(),
                'status'=> 0,
                'url'   => '',
                'data'  => $collect
            );
        }
        $this->ajaxReturn($data);
    }

    function delete(){
        $where['type'] = I('request.type');
        $where['rec_id'] = I('request.id');
        $where['user_id'] = $this->userid;
        $result = $this->_model->where($where)->delete();
        if($result !== false){
            $this->success($where['rec_id']);
        }else{
            $this->error('操作失败！'.$this->_model->getDbError());
        }
    }

    function deleteColorboard(){
        $where['type'] = I('request.type');
        $where['rec_id'] = I('request.id');
        $where['user_id'] = $this->userid;
        $result = $this->_colorboard->where($where)->delete();
        if($result !== false){
            $this->success($where['rec_id
            ']);
        }else{
            $this->error('操作失败！'.$this->_model->getDbError());
        }
    }

    function addColorboard(){
        $where['type'] = I('request.type');
        $where['rec_id'] = I('request.id');
        $where['user_id'] = $this->userid;
        $result = $this->_colorboard->where($where)->delete();
        if($result !== false){
            $this->success($where['rec_id']);
        }else{
            $this->error('操作失败！'.$this->_model->getDbError());
        }
    }
}