<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2017-01-17
 * Time: 12:24
 */

namespace Sms\Controller;


use Common\Controller\HomebaseController;
use Think\Controller;
use Sms\Common\AlidayuSms;

class SendController extends HomebaseController
{
    protected $_model;

    protected $config = array(
        'appkey'    => '23600529',
        'secretKey' => 'a5adb9f3dcd3450db9348ba5f4322e38',
        'format'    => 'json',
    );

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('Sms/Sms');
    }

    function check_code($code, $extend=null){
        list($result, $error_code) = $this->_model->checkCode($code, $extend);
        if($result === true){
            $this->success('');
        }else{
            if($error_code == 'EXPIRED'){
                $err = '验证码已过期';
            }else{
                $err = '验证码错误';
            }
            $this->error($err);
        }
    }

    function send_code(){
        if(IS_POST){
            $post = I('post.');
            $api = new AlidayuSms($this->config);

            $to = $post['to'];
            $extend = $post['extend'];

            $param = array(
                'code'      => build_verify_no(),
                'product'   => '面料馆',
            );
            $tpl_code = 'SMS_41410009';
            $sign_name = '身份验证';
            list($exception, $resp) = $api->send($to, $param, $tpl_code, $sign_name, $extend);

            $log = array(
                'to'    => $to,
                'usage' => 'CODE',
                'code'  => $param['code'],
                'content'   => '',
                'status'    => is_null($exception) && $resp['success'] == true ? 1:0,
                'error_code'=> is_null($exception) ? '':$exception['sub_code'],
                'error_msg' => is_null($exception) ? '':$exception['sub_msg'],
                'used'      => 0,
                'smeta'     => json_encode(array(
                    'param' => $param,
                    'tpl'   => $tpl_code,
                    'sign'  => $sign_name,
                ),256),
                'expire_time'   => date('Y-m-d H:i:s', time() + 60 * 15),
                'result'    => is_null($exception) ? $resp:$exception,
            );
            $result = $this->_model->logSms($log);
            if($result !== false){
                if($exception){
                    $this->error($exception['sub_msg']);
                }elseif($resp['success'] !== true){
                    $this->error('验证码发送失败');
                }else{
                    $result = array(
                        'status'    => 1,
                        'data'      => $resp,
                    );
                    $this->ajaxReturn($result);
                }
            }else{
                $this->error('验证码发送失败');
            }
        }
    }

}