<?php
namespace Supplier\Controller;

use Common\Controller\AdminbaseController;

class AdminSingleController extends AdminbaseController
{
    protected $_model;
    protected $mid;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('BizMember');
        if (isset($_REQUEST['mid'])) {
            $this->mid = I('request.mid');
            $this->assign('mid', $this->mid);
        } else {
            if (!IS_POST) {
                $this->error('请选择供应商！');
            }
        }
    }

    public function bizinfo()
    {
        $member = $this->_model->getMember($this->mid);
        $this->assign($member);
        $this->display();
    }
    
    public function editinfo()
    {
        $member=$this->_model->getMember($this->mid);
        $this->assign($member);

        $this->assign('areas', D('Areas')->getAreasByDistrict($member['auth']['auth_district']));

        $this->display();
    }

    public function editinfo_post()
    {
        if (IS_POST) {
            $post = I('post.');
            $result = $this->_model->saveMember($post);

            $contact = $post['contact'];
            $contact['member_id'] = $post['id'];
            $result2 = D('BizContact')->saveContact($contact);

            if ($result !== false) {
                $this->success('资料已更新！');
            } else {
                $this->error($this->_model->getError());
            }
        }
    }

    public function fans()
    {
        $id = $this->mid;
        $list = D('Fans')->getFansPaged("member_id:$id;");
        $this->assign('list', $list);
        $this->display();
    }

    public function delete_fans()
    {
        if (IS_POST) {
            $fans_model = D('Supplier/Fans');
            $id = I('post.id');
            $result = $fans_model->where(array('id'=>$id))->delete();
            if ($result !== false) {
                $this->ajaxReturn(array(
                    'url'       => U('fans', array('mid' => $this->mid)),
                    'status'    => 1,
                    'info'      => '好友已删除！',
                    'data'      => array('id'=>$id),
                ));
            } else {
                $this->error($fans_model->getError());
            }
        }
    }

    public function fans_level_post()
    {
        if (IS_POST) {
            $post = I('post.');
            $_model = D('Fans');
            $result = $_model->setLevel($post['id'], $post['level']);
            if ($result !== false) {
                $this->success('');
            } else {
                $this->error($_model->getError());
            }
        }
    }
}
