<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2017-01-09
 * Time: 15:51
 */

namespace Supplier\Controller;


use Common\Controller\HomebaseController;

class CustomerController extends HomebaseController
{
    protected $customer_model;
    protected $customer_status = 1;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->customer_model = D('Supplier/Customer');
    }

    public function index(){
        $where = array();
        $where['customer_status'] = $this->customer_status;
        $where['supplier_id'] = sp_get_current_userid();
        $customers = $this->customer_model->getCustomersPaged($where);

        $this->assign('customers', $customers);
        $this->display();
    }

    public function add(){

        $this->display();
    }

    public function add_post(){
        if(IS_POST){
            $data = I('post.');
            $data['add_time'] = time();
            $data['supplier_id'] = sp_get_current_userid();
            $result = $this->customer_model->saveCustomer($data);
            if($result){
                $this->redirect('index');
            }else{
                $this->error($this->customer_model->getError());
            }
        }
        $this->display();
    }

    public function edit(){

        $customer = $this->customer_model->getcustomer($_GET['id']); 
      
        $this->assign("customer",$customer);

        $this->display();
    }

    public function edit_post(){
        if(IS_POST){

            $data = I('post.');
            $data['add_time'] = time();
            $data['supplier_id'] = sp_get_current_userid();
            $result = $this->customer_model->saveCustomer($data);
            if($result){
                $this->redirect('index');
            }else{
                $this->error($this->customer_model->getError());
            }
        }
        $this->display();
    }

    function delete(){
        if(IS_POST){
            $id = I('post.id');
            $customer = $this->customer_model->where(array('id'=>$id))->find();
            if($customer){
                $result = $this->customer_model->where(array('id'=>$id))->save(array('customer_status'=>0));
                if($result !== false){
                    $this->success('操作成功！',leuu('index'));
                }else{
                    $this->error($this->customer_model->getError());
                }
            }else{
                $this->error('错误的操作！');
            }
        }
    }

}