<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2017-01-21
 * Time: 15:13
 */

namespace Supplier\Controller;


use Common\Controller\SupplierbaseController;

class InviteController extends FansController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function index(){
        $this->display();
    }
}