<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2017-04-18
 * Time: 15:51
 */

namespace Supplier\Controller;


use Common\Controller\SupplierbaseController;

class ShareController extends SupplierbaseController
{
    protected $share_model;


    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->share_model = D('Supplier/Share');
    }

    public function index(){
        if(sp_is_mobile()){
            $where = array();
            $where['target_type'] = 2;
            if(I("get.id")){
                $where['target_id'] = I("get.id");
            }
            $status = I("get.status");
            if(isset($_REQUEST['status']) && $status==1){
                $where['UNIX_TIMESTAMP(expire_time)'] = array('egt',time());
                $where['_string'] = "share_num < share_limit";  
            }elseif(isset($_REQUEST['status']) && $status==0){
                $where['_string'] = "share_num >= share_limit OR UNIX_TIMESTAMP(expire_time) <".time();  
            }
            
            $where['supplier_id'] = $this->memberid;
            $shares = $this->share_model->getSharePaged($where);
            
            $this->assign('shares', $shares); 
        }else{
            $where = array();
            $where['target_type'] = I("get.target_type");
            $where['supplier_id'] = $this->memberid;
            
            $shares = $this->share_model->getSharePaged($where);
           

            $this->assign('shares', $shares);
        }
      
        $this->display();
    }

    public function add(){
        if(sp_is_mobile()){
            $member_id = $this->memberid;
            $card = D('Colorcard/Colorcard')->getCard(I('get.id'));
            $this->assign("card",$card);

        }else{
            $member_id = $this->memberid;

            $fans_model = D('Supplier/Fans');
        
            $fansList = $fans_model->getFansNoPaged("member_id:$member_id;");
            $this->assign('fans_list', $fansList);

            $tag = array('ispublic'=>0,'vend_id'=>$member_id,'status'=>1);
            $tfs = D('Tf/Tf')->getTfNoPaged($tag);
            $this->assign('tf_list', $tfs);
            $ispublic = 0;
            $where = array('supplier_id'=>$member_id,'card_status'=>20,'ispublic'=>0,"card_type"=>2,'card_trash'=>0);
            $cards = D('Colorcard/Colorcard')->getCardsNoPaged($where);
            $this->assign('card_list', $cards);
        }
        

        

        $this->display();
    }
    

    public function add_post(){
        if (IS_POST) {
            if(sp_is_mobile()){
                $post = I('post.');
                $post['user_id'] = 0;
                $post['share_pass'] = $post['share_pass'];
                $post['supplier_id'] = $this->memberid;

                $post['expire_time'] = date("Y-m-d H:i:s",86400*$post['expire_time']+time());
                $post['create_time'] = date("Y-m-d H:i:s",time());

                $share_all = D('Supplier/Share')->where(array('target_id'=>$post['target_id'],'user_id'=>0,'target_type'=>2))->find();
        
                if($share_all['share_limit'] == $share_all['share_num']){
                    $post['share_num']=0;
                }

                $result = D('Supplier/Share')->saveShare($post);
                if($result !== false){
                    $this->success('保存成功！');
                }else{
                    $this->success('保存失败！');
                }  
            }else{
                $post = I('post.');
                if (empty($post['target_type'])) {
                    $this->error('请至少选择一种分享类型！');
                }
                if(!empty($post['fans'])){
                    
                    if($post['target_type']==1){
                        $post['target_id'] = $post['tf'];
                    }else{
                        $post['target_id'] = $post['card'];
                    }
                    $post['user_id'] = $post['fans'];
                    $post['share_pass'] = $post['share_pass'];
                    $post['create_time'] = date("Y-m-d H:i:s",time());
                    $post['supplier_id'] = $this->memberid;
                    $this->share_model->saveShare($post);
                    
                    $this->success('分享成功！',leuu('index',array('target_type'=>1)));
                }else{
                    if($post['target_type']==1){
                        $post['target_id'] = $post['tf'];
                    }else{
                        $post['target_id'] = $post['card'];
                    }
                    $post['user_id'] = 0;
                    $post['share_pass'] = $post['share_pass'];
                    $post['supplier_id'] = $this->memberid;
                    $result = $this->share_model->saveShare($post);
                    if($result !== false){
                        $this->success('分享成功！',leuu('index',array('target_type'=>1)));
                    }else{
                        $this->success('分享失败！');
                    }
                }  
            }
                
        }
    }

    function delete(){
        if(IS_POST){
            $id = I('post.id');
            $share = $this->share_model->where(array('id'=>$id))->find();
            if($share){
                $result = $this->share_model->where(array('id'=>$id))->delete();
                if($result !== false){
                    $this->ajaxReturn(array(
                        'status'    => 1,
                        'info'      => '该分享已删除！',
                        'data'      => array('id'=>$id),
                    ));
                }else{
                    $this->error($this->share_model->getError());
                }
            }else{
                $this->error('错误的操作！');
            }
        }
    }

    public function edit(){

        $shares = $this->share_model->getShares($_GET['id']); 

        $member_id = $this->memberid;

        $fans_model = D('Supplier/Fans');
       
        $fansList = $fans_model->getFansNoPaged("member_id:$member_id;");
        $this->assign('fans_list', $fansList);

        $tag = array('ispublic'=>0,'vend_id'=>$member_id,'status'=>1);
        $tfs = D('Tf/Tf')->getTfNoPaged($tag);
        $this->assign('tf_list', $tfs);
        $ispublic = 0;
        $where = array('supplier_id'=>$member_id,'card_status'=>20,'ispublic'=>0,"card_type"=>2,'card_trash'=>0);
        $cards = D('Colorcard/Colorcard')->getCardsNoPaged($where);
        $this->assign('card_list', $cards);
      
        $this->assign("shares",$shares);

        $this->display();
    }

    public function edit_post(){
        if (IS_POST) {
            $post = I('post.');
            if (empty($post['target_type'])) {
                $this->error('请至少选择一种分享类型！');
            }
            if(!empty($post['fans'])){
                if($post['target_type']==1){
                    $post['target_id'] = $post['tf'];
                }else{
                    $post['target_id'] = $post['card'];
                }
                $post['user_id'] = $post['fans'];
                $post['supplier_id'] = $this->memberid;
                $result = $this->share_model->saveShare($post);
                if($result !== false){
                    $this->success('修改分享成功！');
                }else{
                     $this->success('修改分享失败！');
                }
            }else{
                if($post['target_type']==1){
                    $post['target_id'] = $post['tf'];
                }else{
                    $post['target_id'] = $post['card'];
                }
                $post['user_id'] = 0;
                $post['supplier_id'] = $this->memberid;
                $result = $this->share_model->saveShare($post);
                if($result !== false){
                    $this->success('修改分享成功！');
                }else{
                     $this->success('修改分享失败！');
                }
            }      
        }
    }

    function share_url(){
        $data = shortUrl($_GET['share_url']);
        $this-> ajaxReturn($data);
    }




}
