<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2017-05-26
 * Time: 14:32
 */

namespace Tf\Controller;


use Common\Controller\AdminbaseController;

class AdminShelvesController extends AdminbaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index() {
        $shelves = array($this->getShelves(0),$this->getShelves(1));
        $this->assign('shelves', $shelves);
        $this->display(':shelves');
    }

    private function getShelves($onSale=1){
        $tfModel = M('TextileFabric');
        $field = 'tf.id,tf.name,tf.code,tf.img,tf.ispublic';
        //IFNULL(shelves.on_sale,0) as on_sale
        $where['tf.status'] = 1;
        $where['IFNULL(shelves.on_sale,0)'] = $onSale ? 1:0;
        $data = $tfModel->alias('tf')->field($field)
            ->join('LEFT JOIN __TEXTILE_FABRIC_SHELVES__ shelves ON shelves.tf_id=tf.id')
            ->where($where)
            ->select();
        foreach($data as $k => $v){
            $img = json_decode($v['img'], true);
            $data[$k]['thumb'] = $img['thumb'];
            unset($data[$k]['img']);
        }
        return $data;
    }

    public function post(){
        if(IS_POST){
            $post = I('post.');
            if(empty($post['ids'])){
                $this->error('保存失败！');
            }

            $tfModel = M('TextileFabric');
            $shelvesModel = M('TextileFabricShelves');

            foreach($post['ids'] as $on_sale => $ids){
                $where['id'] = array('IN', $ids);
                $where['status'] = 1;
                $ids = $tfModel->where($where)->getField('id',true);
                if(!empty($ids)){
                    foreach($ids as $tf_id){
                        $count = $shelvesModel->where("tf_id=$tf_id")->count();
                        if($count > 0){
                            $shelvesModel->where("tf_id=$tf_id")->setField('on_sale', $on_sale);
                        }else{
                            $shelvesModel->add(array(
                                'tf_id'=>$tf_id,
                                'on_sale'=>$on_sale
                            ));
                        }
                    }
                }
            }
            $this->success('已保存货架！');
        }
    }

    public function toggle()
    {
        if (IS_POST) {
            $id = I('post.id/d', 0);
            $value = I('post.value/d', 0);
            if ($id == 0) {
                $this->error('传入数据出错！');
            }

            $where['id'] = $id;

            $tfModel = M('TextileFabric');
            $shelvesModel = M('TextileFabricShelves');
            $tf = $tfModel->field('name')->where($where)->find();

            if(empty($tf)){
                $this->error('该面料不存在！');
            }

            $count = $shelvesModel->where("tf_id=$id")->count();
            if($count > 0){
                $result = $shelvesModel->where("tf_id=$id")->setField('on_sale', $value);
            }else{
                $result = $shelvesModel->add(array(
                    'tf_id'=>$id,
                    'on_sale'=>$value
                ));
            }

            $data['data'] = $shelvesModel->where("tf_id=$id")->getField('on_sale');
            $data['status'] = $result !== false ? 1:0;
            $data['info'] = $tf['name'].'已设为<b>'.($data['data'] ? '已上线':'已下线').'</b>';
            $this->ajaxReturn($data);
        }
    }

}