<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2017-05-10
 * Time: 11:14
 */

namespace Tf\Controller;


use Common\Controller\AdminbaseController;

class AdminDressController extends AdminbaseController
{
    protected $model;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = M('DressModel');
    }

    function models()
    {
        if (IS_AJAX) {
            if (IS_POST) {
                if(isset($_POST['data'])){
                    $post = I('post.');
                    $action = I('post.action');
                    $data = array();
                    $ids = array();
                    if ($action == 'edit') {
                        $ids = array_keys($post['data']);
                        foreach ($post['data'] as $id => $row) {
                            $row['id'] = $id;
                            $exist_num = $this->model->where("id<>$id AND num={$row['num']}")->count();

                            if ($exist_num > 0) {
                                $this->error("模特编号重复！");
                            }

                            $result = $this->model->save($row);

                            if ($result === false) {
                                $data['result'][$id]['state'] = 'error';
                                $data['result'][$id]['msg'] = "操作失败(ID:$id)：" . $this->model->getDbError();
                            }
                        }
                    } elseif ($action == 'create') {
                        foreach ($post['data'] as $key=>$row) {
                            $exist_num = $this->model->where("num={$row['num']}")->count();

                            if ($exist_num > 0) {
                                $this->error("模特编号重复！");
                            }

                            $result = $this->model->add($row);

                            if ($result === false) {
                                $data['result'][$key]['state'] = 'error';
                                $data['result'][$key]['msg'] = "操作失败：" . $this->model->getDbError();
                            }else{
                                $ids[] = $result;
                            }
                        }
                    } elseif ($action == 'remove') {
                        $ids = array_keys($post['data']);
                        $this->model->where(array('id' => array('IN', $ids)))->delete();
                    }
                    $data['data'] = $this->model->where(array('id' => array('IN', $ids)))->select();
                }else{
                    $data['data'] = $this->model->select();
                }

                $data['status'] = 1;
                foreach ($data['data'] as $k => $v) {
                    $data['data'][$k]['real_path'] = empty($v['path']) ? '' : get_thumb_url($v['path'], true, 150);
                }
                $this->ajaxReturn($data);
            }
        } else {
            $this->display();
        }
    }

    function setting(){
        $options_model = M('Options');
        $option_name = 'dress_settings';
        $where = array('option_name'=>$option_name);
        if(IS_POST){
            $post = I('post.options');
            $config = json_encode($post);
            $count = $options_model->where($where)->count();

            if($count){
                $result = $options_model->where("option_name='$option_name'")->setField('option_value',$config);
            }else{
                $data = array(
                    'option_name'=>$option_name,
                    'option_value'=>$config,
                    'autoload'=>0
                );
                $result = $options_model->add($data);
            }
            F($option_name,null);

            $this->success('保存成功！');
        }else{
            $option_value = $options_model->where($where)->getField('option_value');
            $options = json_decode($option_value,true);
            $this->assign('options',$options);
            $this->display();
        }
    }

}