<?php
namespace Tf\Controller;
use Common\Controller\HomebaseController;

class IndexController extends HomebaseController{
    protected $tf_model;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->tf_model = D('TextileFabric');
    }

	function index(){
        $request = I('get.');
        if(isset($request['tfsn'])){
            $fabric = $this->tf_model->getTfByCode(I('get.tfsn'));
        }else{
            $fabric = $this->tf_model->getTf(I('get.id'));
        }

        $this->assign('fabric', $fabric);
        $this->display(":detail");
	}

	function cats($pid=0){
	    $_model = M('TextileFabricCats');
        $data['items'] = $_model->field('id,title as name,code')->where("pid=$pid")->order('listorder ASC, id ASC')->select();
        if($pid > 0){
            $data['names'] = M('TextileFabricName')->field('id,cname as name,code')->where("cid=$pid")->order('id ASC')->select();
        }
        $data['total_count'] = count($data['items']);
        $this->ajaxReturn($data);
    }
	function names($cid){
	    $_model = M('TextileFabricName');
        $data['items'] = $_model->field('id,cname as name,code')->where("cid=$cid")->order('id ASC')->select();
        $data['total_count'] = count($data['items']);
        $this->ajaxReturn($data);
    }
}