<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-15
 * Time: 9:33
 */

namespace Tf\Controller;


use Common\Controller\SupplierbaseController;

class SupplierCardapplyController extends SupplierbaseController
{
    protected $apply_model;
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->apply_model = D('Tf/CardApply');
    }
    

    function index(){
         $where = array();
        if($_REQUEST['filter']){
            $filter = I('request.filter');
            $statuses = array_keys(D('Tf/CardApply')->statuses);
            if(isset($filter['status'])){
                if($filter['status']==-1){
                    $where['apply_status'] = array('IN',$statuses);
                }else{
                    $where['apply_status'] = $filter['status'];
                }
            }

            if (!empty($filter['datestart']) && !empty($filter['datefinish'])) {
                $where['apply_time'] = array('between', strtotime($filter['datestart']).','.strtotime($filter['datefinish']));
            } elseif (!empty($filter['datestart']) && empty($filter['datefinish'])) {
                $where['apply_time'] = array('egt', strtotime($filter['datestart']));
            } elseif (empty($filter['datestart']) && !empty($filter['datefinish'])) {
                $where['apply_time'] = array('elt', strtotime($filter['datefinish']));
            }

            $this->assign('filter',$filter);
            
        }
        
        $where['supplier_id'] = $this->memberid;
        $applys = $this->apply_model->getApplysPaged($where);

        $this->assign('applys', $applys);
        $this->display();
    }

    function view(){
        $id = I('get.id');
        $apply = $this->apply_model->getApply($id);
        $this->assign('apply',$apply);
        // var_dump($id);
        $this->display();
    }

    function deliver_goods(){
        $post = I('post.');
        $post['apply_status'] = 1;
        if(empty($post['id']) || !is_numeric($post['id'])){
            $this->error('申请id不能为空！');
        } 
        if(empty($post['delivery_num'])){
            $this->error('发货单号不能为空！');
        } 
        if(empty($post['action_note'])){
            $this->error('操作备注不能为空！');
        } 

         $apply = $this->apply_model->getApply($post['id']);
        $result = $this->apply_model->save($post);
        if($result){
            //$this->ajaxReturn($result);
            $title = '你申请的色卡到付发货啦！';
            $content = '你申请的色卡到付发货啦！说明：'.$post['action_note'];
            D('Notify/Msg')->sendMsg($apply['user_id'], $title, $content, $this->memberid, $sender_type = 2, $receiver_type = 1);
            $this->success('发货成功');
            
        }else{
            $this->error('发货失败'.$this->apply_model->getError());
        }
    }

}