<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-15
 * Time: 9:33
 */

namespace Tf\Controller;


use Common\Controller\HomebaseController;
use Tf\Service\TfUnionService;

class TfController extends HomebaseController
{
    protected $tf_model;
    protected $tfUnionService;
    function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->tf_model = D('TextileFabric');
        $this->tfUnionService = new TfUnionService();
    }

    function index(){
        if(sp_is_mobile() && !IS_AJAX){
            $this->display();
            exit();
        }

        $fabrics = $this->tf_model->getTfPaged();

        $this->assign('fabrics', $fabrics);

        if(sp_is_mobile() && IS_AJAX){
            $html = $this->fetch('more');
            $fabrics['html'] = $html;
            unset($fabrics['data']);
            $this->ajaxReturn($fabrics);
        }else{
            $this->display();
        }
    }

    function fabric(){
        $request = I('get.');
        if(isset($request['tfsn'])){
            $data = $this->tfUnionService->getTf($request['tfsn']);
        }else{
            $data = $this->tfUnionService->getTf(array('id'=>$request['id'],'source'=>I('get.sr/d',1)));
        }

        if(empty($data)){
            $this->redirect('Tf/List/index');
        }
        $data['supplier'] = D('BizMember')->getMember($data['supplier_id']);

        $supplier_id = $data['supplier_id'];

        if (sp_is_user_login()) {
            $uid = sp_get_current_userid();
            $is_collected = D('Collect/Collect')->collectStatus($data['id'], $uid, 1);
            $this->assign('is_collected', $is_collected);

            $is_collected_vend = D('Collect/Collect')->where(array(
                'user_id'   => $uid,
                'goods_id'  => $supplier_id,
                'type'      => 3,
            ))->count() > 0 ? 1:0;
            $this->assign('is_collected_vend', $is_collected_vend);
            
            if (!empty($_SESSION['user']['member'])) {
                if ($supplier_id != $_SESSION['user']['member']['id']) {
                    $fans = D('Supplier/Fans')->where("user_id=$uid AND member_id=$supplier_id")->find();
                    if ($data['ispublic'] == 0 && $fans['level'] < $data['fans_level']) {
                        $this->error('这是私密面料，联系面料商咨询详细情况！');
                    }
                }
            }
        } else {
            if ($data['ispublic'] == 0) {
                $this->error('这是私密面料，请登陆并且联系面料商咨询详细情况！');
            }
        }


        $this->assign("smeta", $data['img']);
        $this->assign('data', $data);
        $Wx = new \Wx\Common\Wechat();
        list($err, $user_info) = $Wx->api->get_user_info($_SESSION['user']['openid']);

        $this->assign("subscribe", $user_info->subscribe);
        $Wx->api->create_qrcode("shop_" . $supplier_id, 0);

        list($err, $qrcode) = $Wx->api->create_qrcode("shop_" . $supplier_id, 0);
        $this->assign("qrcode_ticket", $qrcode->ticket);

        //手机版上的sku_list
        $sku_list = $this->tfUnionService->getSkuList(array(
            "tf_id"=>$data['id'],
            "original"=>$data['source'],
        ));

        $ysku_list = $nsku_list = array();
        $price_list = array();
        foreach($sku_list as $k=>$v){
            //有货SKU和无货SKU
            if($v['sku_type'] == 1){
                array_push($ysku_list, $v);
            }
            if($v['sku_type'] == 0){
                array_push($nsku_list, $v);
            }
            array_push($price_list, $v['sku_price']);
        }

        $price_list = array_unique($price_list);
        $this->assign('price_list',$price_list);
        $this->assign("ysku_list",$ysku_list);
        $this->assign("nsku_list",$nsku_list);
        $this->assign("sku_list",$sku_list);

//        var_dump($sku_list);
//        exit;

        $addresses = D('Address/Address')->getAddressNoPaged(array('user_id'=>sp_get_current_userid()));
        $this->assign('addresses',$addresses);

        $shippings = D('Shipping')->getShippingNoPaged();
        $this->assign('shippings',$shippings);
        $this->assign('shipping',reset($shippings));

        if(sp_is_user_login()){
            D('History')->addHistory($data['id'],sp_get_current_userid(),$data['vend_id'],1);
        }

        $this->display(":detail");
    }

    function enquiry(){
        if(IS_POST){
           $post = I('post.');
            if(empty($post['note'])){
                $this->error('请输入您的留言！');
            }else{
                $nickname = session('user.nickname');
                $title = '客户对你的面料价格提出询问';
                $href = leuu('tf/tf/fabric', array('id' => $post['tf_id']));
                $content = '客户'.$nickname.'留言：'.$_POST['note'].' <a href="'.$href.'" class="btn-u btn-u-xs">查看面料详情</a>';
                $result = D('Notify/Msg')->sendMsg($post['supplier_id'], $title, $content, sp_get_current_userid(), 1, 2);
                if($result){
                    $this->success('留言成功！');
                }else{
                    $this->error('留言失败！');
                } 
            }    
        }
    }


    function qr(){
        $url = leuu('fabric',array('id'=>I('get.id')),false,true);
        qrcode($url,1);
    }

}