<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-25
 * Time: 16:34
 */

namespace Customer\Controller;


use Common\Controller\CustomerbaseController;
use Wx\Common\Wechat;

class CenterController extends CustomerbaseController
{
    protected $_model;
    protected $users_model;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = D('BizMember');
        $this->users_model = D('Users');
    }

    function index(){
        $uid = $this->userid;
        $collection = D('Collect/Collect')->getCollPaged("user_id:$uid;");
        $this->assign('collection',$collection);
        $this->display();
    }

    function profile(){
        if(!empty($this->user['openid'])){
            $wechat = new Wechat(get_wx_configs());
            $info = $wechat->api->get_user_info($this->user['openid']);
            $this->assign('wx_info', (array)$info[1]);
        }
        $this->assign('user', $this->user);
        $this->display();
    }

    function basic_post(){
        if(IS_POST){
            $post = I('post.');
            $post['member']['id'] = $this->userid;
            $result = $this->_model->updateMember($post['member']);
            if($result !== false){
                session('user',D('Users')->getUser($this->userid));
                $this->success('资料已更新！');
            }else{
                $this->error($this->_model->getError());
            }
        }
    }

    function wx_unbind(){
        if(IS_POST){
            $result = $this->users_model->where(array('id'=>$this->userid))->setField('openid','');
            if($result !== false){
                $user = $this->users_model->getUser($this->userid);
                session('user', $user);
                $this->success('解绑成功！',leuu('profile'));
            }else{
                $this->error('解绑失败！');
            }
        }
    }

    function wx_bind_qr(){
        if(IS_POST){
            $count = $this->users_model->where(array('id'=>$this->userid,'openid'=>''))->count();
            if($count > 0){
                $wx_model = new Wechat(get_wx_configs());
                list($err, $data) = $wx_model->createQr(60, 2, $this->userid);
                if($data){
                    $this->success($data);
                }else{
                    $this->error($err);
                }
            }
        }
    }
}