<?php
/**
 * Created by PhpStorm.
 * User: Vnimy
 * Date: 2016-11-09
 * Time: 16:38
 */

namespace User\Controller;
use Common\Controller\MemberbaseController;
class SettleController extends MemberbaseController
{
    protected $bm_model;
    protected $member;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->bm_model = D('BizMember');
        $this->member = $this->bm_model->getMember(sp_get_current_userid());
        if($this->member['authenticated'] == 1){
            $this->success('您已经入驻本站，无需重复操作！',leuu('index/index'));
        }
        $this->assign($this->member);
    }

    function index(){
        $this->display();
    }

    function id_auth(){
        $this->display();
    }

    function photo_post(){
        if(IS_POST){
            $name = I('post.name');
            $upload_info = D('Settle', 'Service')->authPhotoUpload();
            if($upload_info['status']){
                if($this->member_model->updateAuthPhoto($name, $upload_info['savename'])){
                    $this->ajaxReturn(sp_ajax_return($upload_info,'上传成功！',1));
                }else{
                    $this->error('上传失败！');
                }
            }else{
                $this->error($upload_info['error']);
            }
        }
    }

    function contact_info(){
        $this->display();
    }

    function contact_info_post(){
        if(IS_POST){
            $post = I('post.');
            $post['id'] = $this->member['id'];

            $result = $this->member_model->updateContact($post);
            if($result){
                $this->success('资料已提交！');
            }else{
                $this->error($this->member_model->getError());
            }
        }
    }

    function store_info(){
        $this->display();
    }

    function store_info_post(){
        if(IS_POST){
            $post = I('post.');
            $post['id'] = $this->member['id'];

            if($_FILES){
                $logo_info = D('Settle', 'Service')->avatarUpload();
                if($logo_info['status']){
                    $post['logo'] = $logo_info['savename'];
                }else{
                    $this->error($logo_info['error']);
                }
            }

            $result = $this->member_model->updateMember($post);
            if($result){
                $this->success('资料已提交！');
            }else{
                $this->error($this->member_model->getError());
            }
        }
    }

    function financial(){
        $this->display();
    }

    function financial_post(){
        if(IS_POST){
            $post = I('post.');
            $post['id'] = $this->member['id'];

            $result = $this->member_model->updateFinancial($post);
            if($result){
                $this->success('资料已提交！');
            }else{
                $this->error($this->member_model->getError());
            }
        }
    }

    function confirm(){
        $this->display();
    }

}